<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add Service Provider_MuiBackdrop-root M_4d634a_1</name>
   <tag></tag>
   <elementGuidId>402ac04e-e750-4abe-9d9c-213d5ee5fec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBackdrop-root.MuiBackdrop-invisible.css-z9f4vk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-cityId']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ca6641f6-526b-4c4a-bf35-f6c1790d8420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>57eeacd8-26f7-4c3c-b9e6-dd05e4abc926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBackdrop-root MuiBackdrop-invisible css-z9f4vk</value>
      <webElementGuid>8743c9cf-214e-4c4b-bb0b-9db8ae39f406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-cityId&quot;)/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible css-z9f4vk&quot;]</value>
      <webElementGuid>3fdb6d7f-e0d1-432a-95ed-7631511f7796</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-cityId']/div</value>
      <webElementGuid>8fb9f5cc-0659-4736-96a5-587ff38fa17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>5c315000-6843-4ba3-a0a3-5bcfc8b3ee3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
