<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Company EmailPasswordvisibilityForgot _f23241</name>
   <tag></tag>
   <elementGuidId>da5e1d98-698f-49bd-8595-8fff737b1348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[2]/form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>70a052ca-d3ab-41dd-b3f5-5f321dae8626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company Email *Password *​visibilityForgot password?LoginNot registered yet? Create an account</value>
      <webElementGuid>d2f0fa51-43ba-4481-9a38-9419c2a04573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;MuiGrid-root MuiGrid-container css-1ihe8x4&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-sm-6 css-yjm5xu&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-alznhl&quot;]/div[@class=&quot;MuiCardContent-root css-162ssw6&quot;]/form[1]</value>
      <webElementGuid>07e6a98f-5a3c-4ca9-b2aa-d2210b62e2c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/form</value>
      <webElementGuid>3bedf939-d2ac-47a2-a638-9747415819d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Horizon'])[1]/following::form[1]</value>
      <webElementGuid>bdba73b7-0785-44d0-8afc-54e7a79c2893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>b2af7891-0f85-44ca-bdde-65a3e14bb319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'Company Email *Password *​visibilityForgot password?LoginNot registered yet? Create an account' or . = 'Company Email *Password *​visibilityForgot password?LoginNot registered yet? Create an account')]</value>
      <webElementGuid>c12c854e-94ea-4903-8a5c-9d1fc549ab1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
