<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Company province must be filled</name>
   <tag></tag>
   <elementGuidId>617ea536-6fcc-4d09-bcdb-047e126340ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-18-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='mui-18-helper-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6dbe5394-b316-4d7e-b056-4642cbe6133e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium Mui-required css-xfkq2o</value>
      <webElementGuid>bcf5d794-5d1e-4821-bb87-69ce8253af0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-18-helper-text</value>
      <webElementGuid>ede164bf-5641-4b85-8dbd-c8ee0ac1804c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company province must be filled.</value>
      <webElementGuid>2617614e-1dee-40d9-a051-cc7812578945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-18-helper-text&quot;)</value>
      <webElementGuid>c4454953-087d-48a1-985f-4f585dda399c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='mui-18-helper-text']</value>
      <webElementGuid>ca58d1b0-eaeb-4ab5-aa5a-f7d2c3474c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div/div[2]/div/div/div/div/div/div[6]/p</value>
      <webElementGuid>6d9c6d9c-6aa4-4b6a-8dab-ed1a3208fc27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose province'])[1]/following::p[1]</value>
      <webElementGuid>d0ff166d-4114-4746-a4da-91cfe9f65edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose city'])[1]/preceding::p[1]</value>
      <webElementGuid>55725c4d-576c-4bb7-9c93-a4db04275b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Company province must be filled.']/parent::*</value>
      <webElementGuid>0767de9d-693f-42f1-b2f9-bab0b86fede9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/p</value>
      <webElementGuid>c91f6a6f-708b-4913-a7e2-dfd52d50bba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'mui-18-helper-text' and (text() = 'Company province must be filled.' or . = 'Company province must be filled.')]</value>
      <webElementGuid>ef6070b6-2067-441f-b004-6154806cb46b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
