<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Company country must be filled</name>
   <tag></tag>
   <elementGuidId>8126cda7-320d-4633-b9eb-f55dceaf3b6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-17-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='mui-17-helper-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d4959efb-847e-4a09-ab90-63038255a870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium css-xfkq2o</value>
      <webElementGuid>b0906ad4-a814-4667-82ec-a4d6ae9bd089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-17-helper-text</value>
      <webElementGuid>f0766e69-9dd1-4367-afaf-d25f4bcbc74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company country must be filled.</value>
      <webElementGuid>e120ca83-4eaf-423f-a1e7-dc1f61eb71c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-17-helper-text&quot;)</value>
      <webElementGuid>e0c14dac-5061-45c9-8175-563147f31e96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='mui-17-helper-text']</value>
      <webElementGuid>39515d41-2a78-44da-a129-b4ab1a518f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div/div[2]/div/div/div/div/div/div[5]/p</value>
      <webElementGuid>9d8643f8-8e38-436f-a6a5-a39a356ed1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose country'])[1]/following::p[1]</value>
      <webElementGuid>10a9028b-32be-4d76-a522-54b2ab81bfe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::p[1]</value>
      <webElementGuid>91c87784-3acd-43b9-a06a-98d67afe8c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose province'])[1]/preceding::p[1]</value>
      <webElementGuid>3299c5da-18d9-4829-adff-419d979f901e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Company country must be filled.']/parent::*</value>
      <webElementGuid>5aaf70d2-9e72-44a0-8eb8-b686e5ad7153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/p</value>
      <webElementGuid>53764e8a-907c-4c87-83ee-4eab4b0ef527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'mui-17-helper-text' and (text() = 'Company country must be filled.' or . = 'Company country must be filled.')]</value>
      <webElementGuid>53798cf3-c550-4b31-9282-a756438a3b60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
