<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Company email must be filled</name>
   <tag></tag>
   <elementGuidId>57314be0-52d2-4e8d-8544-148d29e85d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-15-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='mui-15-helper-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>03e38578-dd04-4171-88fb-a7265771a33a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium Mui-required css-xfkq2o</value>
      <webElementGuid>33fe8654-2c22-4d24-af05-61f6abac8034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-15-helper-text</value>
      <webElementGuid>17cf7abb-145c-4691-8e7d-81ba89959621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company email must be filled</value>
      <webElementGuid>81005593-2c2b-4780-9967-ca5de9ed4b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-15-helper-text&quot;)</value>
      <webElementGuid>34f1bf5b-57dc-4ff7-9c33-81e2fdb5c125</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='mui-15-helper-text']</value>
      <webElementGuid>2439b4c1-4f04-4633-b79c-ffc4b5cca7f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div/div[2]/div/div/div/div/div/div[3]/p</value>
      <webElementGuid>a8913f7b-680b-499f-918d-9f240eec1878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::p[2]</value>
      <webElementGuid>0230b179-dea6-4d28-901a-eace7f5ffd6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Company email must be filled']/parent::*</value>
      <webElementGuid>7ba3c5c6-89fe-4784-8550-66d04e1107f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>5da0f406-2573-401a-a0ef-234077cdc923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'mui-15-helper-text' and (text() = 'Company email must be filled' or . = 'Company email must be filled')]</value>
      <webElementGuid>9d33c9e6-bd43-4b00-99ea-bf8a3f9bf623</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
