<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Phone number must be filled</name>
   <tag></tag>
   <elementGuidId>dc6dc70d-00b9-429b-ae25-ffade17359d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-16-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='mui-16-helper-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>dc4764f5-04a8-4ebe-b049-0cd6ed6e0218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium Mui-required css-xfkq2o</value>
      <webElementGuid>21491674-752c-4a0e-bd64-c1e4a979e290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-16-helper-text</value>
      <webElementGuid>8a01da62-77c6-4c92-8b33-834c354956ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phone number must be filled</value>
      <webElementGuid>92aac0a0-a8f1-4f58-9a93-9fd312fbbb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-16-helper-text&quot;)</value>
      <webElementGuid>38afc261-4101-4069-92d6-a641434e23c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='mui-16-helper-text']</value>
      <webElementGuid>76ab2285-1391-47d3-9920-f920cd2175e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div/div[2]/div/div/div/div/div/div[4]/p</value>
      <webElementGuid>a1ecadd5-59d5-414e-bb95-3954d6f05465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::p[1]</value>
      <webElementGuid>20fab558-d64d-464a-93fe-fe3b48226f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose country'])[1]/preceding::p[1]</value>
      <webElementGuid>7f0f302e-d8b6-4e99-b85a-76b1d1971459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Phone number must be filled']/parent::*</value>
      <webElementGuid>4b028e75-fe1e-4813-b995-6588ae95b011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/p</value>
      <webElementGuid>9b3c05d7-9a24-47d5-bf4a-5a084696b776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'mui-16-helper-text' and (text() = 'Phone number must be filled' or . = 'Phone number must be filled')]</value>
      <webElementGuid>291ebc18-084a-4613-bd13-ea8198b3b4cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
