<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login_inputEmail</name>
   <tag></tag>
   <elementGuidId>a07edb49-c300-47b9-b1aa-e5f81cdf7d01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid=&quot;input-login-email&quot;][1]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0808ce3-127e-438c-9825-ea78b4adff93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3b65a002-a93e-4245-ab24-0f029b4f8654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2cbcef24-620d-47cc-b99f-5a8f85825a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input company email</value>
      <webElementGuid>98baa30e-7676-4bc4-8aad-847ffdc26d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>fd14460e-863e-41f8-a5bf-0b40b6ae8a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInput-input MuiInputBase-input css-ix5l9r</value>
      <webElementGuid>aa159c68-9a05-461e-874a-662f075cdfdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-1</value>
      <webElementGuid>276fb6ce-e152-4e64-af37-57736ebe3a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-1&quot;)</value>
      <webElementGuid>fc7ba5f8-d224-406a-a25f-c0fcfca5e689</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-1']</value>
      <webElementGuid>875ec812-fb1f-4d3a-bbf8-48a26c3cff80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/form/div/div/div/input</value>
      <webElementGuid>0e2f6533-f59e-4f59-acd4-e978d51b9ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2278dd27-30c9-4bd7-85ea-902029a566da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @placeholder = 'Input company email' and @type = 'email' and @id = 'mui-1']</value>
      <webElementGuid>6511986d-38be-4f7b-ab56-19943efda390</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
