<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EmptyString_C_province</name>
   <tag></tag>
   <elementGuidId>7da0d804-dd7c-40d8-b93d-d430c39bad9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-38-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid=&quot;input-province&quot;]/p
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e7cf8cab-3e7a-4120-a0d1-15e44ff6a54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium Mui-required css-xfkq2o</value>
      <webElementGuid>ad453d6c-f6f9-4c39-ae3d-14aa6f299955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-38-helper-text</value>
      <webElementGuid>64e6716d-425d-4e11-83cb-4518e2c4675a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company province must be filled.</value>
      <webElementGuid>70c6876d-b7f5-44c6-9ce8-f1af7025d736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-38-helper-text&quot;)</value>
      <webElementGuid>a17df15c-5730-4679-9f64-5632e88ee10d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='mui-38-helper-text']</value>
      <webElementGuid>6380d7e7-029c-4bb6-a9ee-50c0a3cf1e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div/div[2]/div/div/div/div/div/div[6]/p</value>
      <webElementGuid>ba4e2a11-f756-4b54-9c27-84583f484428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose province'])[1]/following::p[1]</value>
      <webElementGuid>95419cb9-2d37-4a0a-96b1-c2b8ed998561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose city'])[1]/preceding::p[1]</value>
      <webElementGuid>67c324bb-8c83-40f0-b3f8-2dc71caf79c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Company province must be filled.']/parent::*</value>
      <webElementGuid>4feeaa99-c099-4c0a-bc0b-085b0e6ff907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/p</value>
      <webElementGuid>4f18d693-46fc-41ec-84b0-d41c4a543f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'mui-38-helper-text' and (text() = 'Company province must be filled.' or . = 'Company province must be filled.')]</value>
      <webElementGuid>65ae0067-b6a9-4db0-8785-9d99a679b93d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
