<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EmptyString_CP_Name</name>
   <tag></tag>
   <elementGuidId>843eb825-82f6-465c-b83c-80ff53b7f007</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-47-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid=&quot;input-name-service-provider&quot;]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f7552180-ac38-4988-9825-6c634af7cda3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium Mui-required css-xfkq2o</value>
      <webElementGuid>3a5ea231-1a66-4bda-94fe-07e66b21b941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-47-helper-text</value>
      <webElementGuid>e30a09e4-2324-41c3-a3c7-6b234c14d46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name must be filled</value>
      <webElementGuid>692059d5-a4e4-45bd-84e3-6d17c439bbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-47-helper-text&quot;)</value>
      <webElementGuid>806803bd-6718-44cf-8548-c3d60e8a2673</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='mui-47-helper-text']</value>
      <webElementGuid>339e1ad3-27e9-452b-9431-faf1d51252f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div[2]/div[2]/div/div/div/div/div/div/p</value>
      <webElementGuid>552b1e05-47da-4041-bb48-3c6710842c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Person'])[1]/following::p[1]</value>
      <webElementGuid>538f9744-c6cb-47d4-99cc-6b598e7f8679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Name must be filled']/parent::*</value>
      <webElementGuid>8c546934-bbc3-4013-aba3-f99e2975525a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/p</value>
      <webElementGuid>d632b328-956a-468f-adc1-6396442456ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'mui-47-helper-text' and (text() = 'Name must be filled' or . = 'Name must be filled')]</value>
      <webElementGuid>a9922e8d-e43d-4091-99bf-e6e96c0ad4e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
