<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EmptyString_C_NPWP</name>
   <tag></tag>
   <elementGuidId>7730dce4-83d8-4bbc-9060-d7e3cddb3afc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-44-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid=&quot;input-company-npwp&quot;]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>84331343-c0da-431c-a48e-633733c60b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium Mui-required css-xfkq2o</value>
      <webElementGuid>43d8603d-2d9f-42de-b33c-0ba4dbd55dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-44-helper-text</value>
      <webElementGuid>c184d80c-614b-46f3-98d0-98eae55bfc39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company NPWP must be filled.</value>
      <webElementGuid>aad9256f-44e3-46be-b50f-bdaafd71372b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-44-helper-text&quot;)</value>
      <webElementGuid>4b16a962-26d7-4711-928a-e4f3a48edf13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='mui-44-helper-text']</value>
      <webElementGuid>06431f07-209a-4d48-88fe-9d71334f3e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div/div[2]/div/div/div/div/div/div[11]/p</value>
      <webElementGuid>2f949ea9-1d55-4b3f-b52a-69dbe84b2ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIUP'])[1]/following::p[2]</value>
      <webElementGuid>bbc8d969-85d3-4038-8b80-bd7a6ce0190d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PKP'])[1]/preceding::p[1]</value>
      <webElementGuid>fc536018-4fb2-4667-81b8-62e19d0e448a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Company NPWP must be filled.']/parent::*</value>
      <webElementGuid>b761076e-b3e6-4825-a90c-101191f271cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/p</value>
      <webElementGuid>f80efe3c-9725-4452-b453-e0c8ec7ed3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'mui-44-helper-text' and (text() = 'Company NPWP must be filled.' or . = 'Company NPWP must be filled.')]</value>
      <webElementGuid>4974621b-9bdd-4215-95f5-c1742f425bf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
