<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mptyString_CP_Email</name>
   <tag></tag>
   <elementGuidId>0f2bd571-69a7-4f47-a5ac-14815c93d7a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-48-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='mui-48-helper-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>00d9d6d7-8034-4a55-afce-c733e97888b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium Mui-required css-xfkq2o</value>
      <webElementGuid>5e444bfb-3cbc-41e3-b416-9808db961786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-48-helper-text</value>
      <webElementGuid>cc1e215a-e459-477b-a7d9-24dbc86f182b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email must be filled</value>
      <webElementGuid>a7c75dca-ac9e-43ef-a330-d4dccda5f824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-48-helper-text&quot;)</value>
      <webElementGuid>1150b8c4-ac30-4129-bdee-8585b17cda65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='mui-48-helper-text']</value>
      <webElementGuid>0b267e3f-bac6-434a-b153-f3aac292e0a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div[2]/div[2]/div/div/div/div/div/div[2]/p</value>
      <webElementGuid>7eadbc11-62b2-4402-a476-18da98cc115f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::p[2]</value>
      <webElementGuid>0592c559-eaba-4127-bf6c-a266f1373a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email must be filled']/parent::*</value>
      <webElementGuid>37ce0f12-ebeb-4f0b-8e66-399e970f2737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div[2]/p</value>
      <webElementGuid>3ed70e3f-6f23-4e77-9e7e-afee85333658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'mui-48-helper-text' and (text() = 'Email must be filled' or . = 'Email must be filled')]</value>
      <webElementGuid>de8cb2b7-c78d-4a41-b7d7-f3d5b922e864</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
