<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mptyString_C_Password</name>
   <tag></tag>
   <elementGuidId>c11d1fe6-0bc9-4514-9992-cddc71e7abc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-50-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid=&quot;input-add-service-provider-password&quot;]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f1df30b1-7c92-47d2-8981-ad077ad838bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium Mui-required css-xfkq2o</value>
      <webElementGuid>c6f6ac2e-2fde-4fbf-9b26-e7fa082324d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-50-helper-text</value>
      <webElementGuid>e5223597-a741-4175-9b28-ec376ba55b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password must contain minimal 8 characters, maximal 50 characters, one uppercase, one lowercase, one number, one special case character (!@#$%^&amp;*.), and no spaces.</value>
      <webElementGuid>27799e20-452b-4ecc-a848-c8ccd705aa28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-50-helper-text&quot;)</value>
      <webElementGuid>9ecadfbe-784e-46a4-87ef-7098b81c6122</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='mui-50-helper-text']</value>
      <webElementGuid>e19ea2a3-e77d-45e0-b4b9-a28cb598fd28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div[3]/div[2]/div/div/div/div/div/div/p</value>
      <webElementGuid>583abfa7-0672-4b11-a84b-1487713db224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::p[1]</value>
      <webElementGuid>14201b04-32c6-4647-bcdc-a0dd9f9a1177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/preceding::p[1]</value>
      <webElementGuid>3a74c412-9300-41b9-a601-695431a31ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password must contain minimal 8 characters, maximal 50 characters, one uppercase, one lowercase, one number, one special case character (!@#$%^&amp;*.), and no spaces.']/parent::*</value>
      <webElementGuid>7aaee349-36bd-4bc6-9361-c3619af58047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div/div/p</value>
      <webElementGuid>952ffd6a-e7c7-49a2-a724-dd116e1251bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'mui-50-helper-text' and (text() = 'Password must contain minimal 8 characters, maximal 50 characters, one uppercase, one lowercase, one number, one special case character (!@#$%^&amp;*.), and no spaces.' or . = 'Password must contain minimal 8 characters, maximal 50 characters, one uppercase, one lowercase, one number, one special case character (!@#$%^&amp;*.), and no spaces.')]</value>
      <webElementGuid>9ed13cf5-65a2-4495-b899-32c3394b9743</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
