<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>listCity</name>
   <tag></tag>
   <elementGuidId>a78575e3-0581-4d6d-833d-5f719066d446</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#autocomplete-search-by-city-option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='autocomplete-search-by-city-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>003b81f6-ace9-4efe-a442-7840eb6d0504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option MuiBox-root css-0 Mui-focused</value>
      <webElementGuid>ecdd9472-d6a3-4a38-a457-200115659eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>42ffa788-9c6c-4d59-9a13-ad5faa1aa06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>4e81c8dc-cf87-48b4-bc67-ed8978f8df29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autocomplete-search-by-city-option-0</value>
      <webElementGuid>6af369ef-0b52-4682-9af8-d5b7f7e33689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c666100b-0f0e-49bf-a394-68dea3248fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>98b8e00d-d1a0-46ad-9ca8-3a7824a1e47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cf14e825-5e0c-4df2-a6a9-1032ee98724c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BULUNGAN</value>
      <webElementGuid>63af9041-655a-4281-bb92-fa0ab69a31b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autocomplete-search-by-city-option-0&quot;)</value>
      <webElementGuid>6b8ec4ab-7103-431d-b848-e1a658656afa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='autocomplete-search-by-city-option-0']</value>
      <webElementGuid>488b89f0-6c3d-4fab-833a-3023117dea8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='autocomplete-search-by-city-listbox']/li</value>
      <webElementGuid>3b245139-5b96-4a5b-bd4f-1991523a87f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'autocomplete-search-by-city-option-0', '&quot;', ')')])[1]/following::li[1]</value>
      <webElementGuid>3d0cd540-dd0d-4f00-97cd-0b89044cf3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIVE'])[6]/following::li[1]</value>
      <webElementGuid>e317f4bb-06a6-429b-8b40-1130ca34f2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li</value>
      <webElementGuid>b8c7a9f2-7fd5-4136-b192-032cae62cb93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'autocomplete-search-by-city-option-0' and (text() = 'BULUNGAN' or . = 'BULUNGAN')]</value>
      <webElementGuid>903fd282-2797-4693-9e9e-91a76d9d4d52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
