<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>0f9ae046-70e4-4eb7-96d1-d9414c2d9f79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mui-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fefc24d8-6458-43c0-a6d3-7aa5404376e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2526be07-80ae-4162-bbb8-018b77e83276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ed39fdf4-6eb5-45c3-b260-ca74a3f20df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input password</value>
      <webElementGuid>b27b8330-28aa-4876-a01b-d8485938eb4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>641f8fa3-965f-4ae7-9103-ea86d6ac1dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInput-input MuiInputBase-input MuiInputBase-inputAdornedEnd css-ix5l9r</value>
      <webElementGuid>d99c7b57-852d-4d04-8f62-076112a24004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-2</value>
      <webElementGuid>e7dd0770-4309-4ba9-bb67-f5e5cfaa9efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-2&quot;)</value>
      <webElementGuid>d422c5ac-9e0c-41f2-8ba9-e243f3c213b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-2']</value>
      <webElementGuid>e0f3aa2f-e77a-4468-89a2-cbe1f2ceb92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/form/div/div[2]/div/input</value>
      <webElementGuid>b116ea99-a3a6-475f-b327-185042a5cf26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>fc3f53fe-86d0-439d-bdc9-244e16a8a98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @placeholder = 'Input password' and @type = 'password' and @id = 'mui-2']</value>
      <webElementGuid>7b9b5b34-fdf8-4d68-b146-6be60e997fc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
