<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddSP_input_Password</name>
   <tag></tag>
   <elementGuidId>d08e4f5a-f469-4caa-8645-9254feb8197f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-20</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid=&quot;input-add-service-provider-password&quot;]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bd26a10-1cfd-4057-b6dd-61a95d0b3f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ad1505cb-cb39-4120-800c-1692c32f2fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a4264de3-a653-4f98-bad4-d876840f406e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input password</value>
      <webElementGuid>9e08b2c9-9363-42ec-b1db-a4ff04f0e311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9cfa04f4-3d69-4114-babd-8066cd3ce53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInput-input MuiInputBase-input MuiInputBase-inputAdornedEnd css-ix5l9r</value>
      <webElementGuid>9935ef5d-978a-41d4-8675-f7029229eb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-20</value>
      <webElementGuid>33bad926-80f0-4cdb-b403-93e799cdcf8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-20&quot;)</value>
      <webElementGuid>29d5c0ff-b7db-40d1-8463-db8dc5d3c915</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-20']</value>
      <webElementGuid>5bf03be0-3415-4398-9446-df9c0efbe830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div[3]/div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>5c541c9b-57e7-42ef-a4b8-396e04401cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>126b1988-2aca-471d-8a0a-ce823781acdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @placeholder = 'Input password' and @type = 'password' and @id = 'mui-20']</value>
      <webElementGuid>deedf389-2a4e-4bd1-933c-f1cccded68d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
