<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddSP_input_NPWP_taxId</name>
   <tag></tag>
   <elementGuidId>4e163c11-f515-4798-a843-2dcc6103ee58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid=&quot;input-company-npwp&quot;]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec668ded-add7-43d7-be1a-22e3d2b5a286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f4d365ae-4c71-4e95-aa6f-585c0744d10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>taxId</value>
      <webElementGuid>035dc1ca-1506-462e-96c2-f1ae9feeef09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input NPWP</value>
      <webElementGuid>4b9403ea-48e7-4d90-95d3-acaf7b48b843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0ce35a8-b71f-4518-bb2d-66ea76c49851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInput-input MuiInputBase-input css-ix5l9r</value>
      <webElementGuid>b2e324f7-316c-4210-ab74-86192a45f202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-16</value>
      <webElementGuid>1ab8d495-cd24-4b69-9c52-dc3896abfe3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-16&quot;)</value>
      <webElementGuid>1aa4bbc3-8f2d-4f6e-bdc4-29bee4817903</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-16']</value>
      <webElementGuid>5220b13f-3afe-4404-a0ea-e7d166a49049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div/div[2]/div/div/div/div/div/div[11]/div/input</value>
      <webElementGuid>816b4c5e-76c0-449a-abca-57659cb7f9d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/input</value>
      <webElementGuid>2c7472cd-d73b-4758-acb0-e03fbc9af022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'taxId' and @placeholder = 'Input NPWP' and @type = 'text' and @id = 'mui-16']</value>
      <webElementGuid>b9257c93-aac8-4792-8e3b-39feeccc0a7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
