<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddSP_input_Confirmation Password</name>
   <tag></tag>
   <elementGuidId>43fd3c3b-4fd4-4e28-8ef1-9a06a875039c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid=&quot;input-add-service-provider-confirmation-password&quot;]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-21</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'confirmPassword' and @placeholder = 'Input confirmation password' and @type = 'password' and @id = 'mui-21']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af10f5fb-c1ae-414c-b7ad-dc7cd5e51c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>96993629-339f-4ee4-8ac1-0402bb346a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>f997a8e4-9dfd-4ac0-88f9-7b35e5cac6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input confirmation password</value>
      <webElementGuid>8a7ab866-9f39-4627-bba8-f3d3f558d18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7875979b-e3df-44fa-936b-fd7db79a598b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInput-input MuiInputBase-input MuiInputBase-inputAdornedEnd css-ix5l9r</value>
      <webElementGuid>f6968933-44da-416a-84c5-31994eff76cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-21</value>
      <webElementGuid>9c8ab2aa-57a3-4354-8e5e-73401b1fe1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-21&quot;)</value>
      <webElementGuid>b8097a45-f406-4ac1-b342-c4c7fd22fcad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-21']</value>
      <webElementGuid>700e04e7-2729-4038-9ae4-9062c8f94fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div[3]/div[2]/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>35b69827-aa5f-470d-b7af-0ef40e697274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>da80ea1e-c359-4760-8c79-24ceeacd5e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'confirmPassword' and @placeholder = 'Input confirmation password' and @type = 'password' and @id = 'mui-21']</value>
      <webElementGuid>12eafeee-1d9a-489f-a2e2-e1215d3bd8ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
