<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddSP_CP_input_Phone Number</name>
   <tag></tag>
   <elementGuidId>d4dbcfb0-d8dd-4324-a8d7-dabbeac269a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid=&quot;input-phone-number-service-provider&quot;]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a80a1643-0757-4a82-b103-0467abb126b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>53e0c6aa-18ca-466e-8c07-d986548c78a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>bd40a5f7-a5a5-4b12-9453-62ae2b584602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input phone number</value>
      <webElementGuid>28fcd85b-e578-4b7a-b992-7fd0e8d77b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6c9cbfe-bdeb-46ab-92cd-80dc4f76a420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInput-input MuiInputBase-input css-ix5l9r</value>
      <webElementGuid>bb13d83c-5538-4fbf-bf58-edfd150f6d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-19</value>
      <webElementGuid>b68dbd52-e315-4576-bad7-348e0491e404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-19&quot;)</value>
      <webElementGuid>1d1172cf-71eb-4d60-8d8c-6508f501295f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-19']</value>
      <webElementGuid>cf2ba4e6-e1fd-4d0e-b916-c93a0bb51dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div[2]/div[2]/div/div/div/div/div/div[3]/div/input</value>
      <webElementGuid>b411e2e0-51d7-4ce6-a92f-79972121ed17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div[3]/div/input</value>
      <webElementGuid>e767e025-4e4f-4b96-85b9-49a532611177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'phone' and @placeholder = 'Input phone number' and @type = 'text' and @id = 'mui-19']</value>
      <webElementGuid>ae39eca2-e20c-434b-b25b-8aee5c6448f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
