<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Company dropdown password</name>
   <tag></tag>
   <elementGuidId>174edfd5-8746-4c4a-a8c2-8d2ef7702062</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-sm-12.MuiGrid-grid-md-12.MuiGrid-grid-lg-8.css-1srxrdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div/main/div[2]/div/div[3]/div[1]/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20fb2db0-be3f-4ebe-adaf-e053011f105c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiGrid-root MuiGrid-item MuiGrid-grid-sm-12 MuiGrid-grid-md-12 MuiGrid-grid-lg-8 css-1srxrdd</value>
      <webElementGuid>68f8f93f-8cb8-40ec-9d26-21dbdd3298fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company Detailsarrow_drop_downCompany IDCompany Name *Email *Phone Number *CountryIndonesiaProvince *SUMATERA UTARACity *MEDANPost CodeAddressCompany Document *SIUPNPWP *Company Tax *PKPNon-PKPType Of Service *Full Truck Load help_outlineLess Truck Load help_outlineCompany Logo *minimum image size 100 x 100 (max. 200 Kb) extension file must be in .PNGUpload Company LogoContact Personarrow_drop_downName *Email *Phone Number *Passwordarrow_drop_downPassword *​visibility_offConfirmation Password *​visibility_offCancelAdd Service Provider</value>
      <webElementGuid>bc36e9ce-e690-4701-b6a7-86db7070fa00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-k008qs&quot;]/main[@class=&quot;MuiBox-root css-4rrr9a&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-1cn3yto&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-sm-12 MuiGrid-grid-md-12 MuiGrid-grid-lg-8 css-1srxrdd&quot;]</value>
      <webElementGuid>b83adeb9-1489-434d-b2b7-7db26d09dd01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div</value>
      <webElementGuid>680c1ccd-c37e-443b-ab04-e5b6114cc0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]/div</value>
      <webElementGuid>de8d98cd-77d1-42e2-9678-aaa66d878302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Company Detailsarrow_drop_downCompany IDCompany Name *Email *Phone Number *CountryIndonesiaProvince *SUMATERA UTARACity *MEDANPost CodeAddressCompany Document *SIUPNPWP *Company Tax *PKPNon-PKPType Of Service *Full Truck Load help_outlineLess Truck Load help_outlineCompany Logo *minimum image size 100 x 100 (max. 200 Kb) extension file must be in .PNGUpload Company LogoContact Personarrow_drop_downName *Email *Phone Number *Passwordarrow_drop_downPassword *​visibility_offConfirmation Password *​visibility_offCancelAdd Service Provider' or . = 'Company Detailsarrow_drop_downCompany IDCompany Name *Email *Phone Number *CountryIndonesiaProvince *SUMATERA UTARACity *MEDANPost CodeAddressCompany Document *SIUPNPWP *Company Tax *PKPNon-PKPType Of Service *Full Truck Load help_outlineLess Truck Load help_outlineCompany Logo *minimum image size 100 x 100 (max. 200 Kb) extension file must be in .PNGUpload Company LogoContact Personarrow_drop_downName *Email *Phone Number *Passwordarrow_drop_downPassword *​visibility_offConfirmation Password *​visibility_offCancelAdd Service Provider')]</value>
      <webElementGuid>8f5c6648-ad0b-4f99-8946-3d7cb2aa2297</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
