<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>get Detail SP arrow</name>
   <tag></tag>
   <elementGuidId>7bccaefd-d483-4200-bd35-1a67badea760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div/main/div[2]/table/tbody/tr/td[7]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.material-icons-outlined.notranslate.MuiIcon-root.MuiIcon-fontSizeSmall.css-1qj2lzh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e1bd7bf8-463a-49b3-8a2d-960d4a7081f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons-outlined notranslate MuiIcon-root MuiIcon-fontSizeSmall css-1qj2lzh</value>
      <webElementGuid>c795aaaa-4e41-42b8-9e74-0a7e3ed2ebb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dc1c28c4-718e-4e87-b6ad-9c6b8169d60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>icon-detail-service-provider-IDN0098</value>
      <webElementGuid>1aa36431-df9b-48e2-a418-6d4ff3f83919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>arrow_forward</value>
      <webElementGuid>44fb1181-7fad-4337-a939-20d5eeb3a8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-k008qs&quot;]/main[@class=&quot;MuiBox-root css-4rrr9a&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiTableContainer-root css-10lmdw7&quot;]/table[@class=&quot;MuiTable-root css-12t2pvv&quot;]/tbody[@class=&quot;MuiTableBody-root css-1xnox0e&quot;]/tr[@class=&quot;MuiTableRow-root css-10xs750&quot;]/td[@class=&quot;MuiTableCell-root MuiTableCell-body MuiTableCell-sizeMedium css-pyzizp&quot;]/a[@class=&quot;MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineHover css-hgqhmt&quot;]/span[@class=&quot;material-icons-outlined notranslate MuiIcon-root MuiIcon-fontSizeSmall css-1qj2lzh&quot;]</value>
      <webElementGuid>03bdff2d-f331-4ab3-b851-ab0cc0b651e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/table/tbody/tr/td[7]/a/span</value>
      <webElementGuid>9cc82a37-94bf-41a8-956d-b55d10157b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIVE'])[1]/following::span[1]</value>
      <webElementGuid>9b08c4da-a3f2-4ac0-b58f-a0ec97dee84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BULUNGAN'])[1]/following::span[2]</value>
      <webElementGuid>f085cae2-0db3-475f-ad17-806c7ee8707b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='arrow_forward']/parent::*</value>
      <webElementGuid>ad24ceb0-bf87-4b7f-be36-9b30103360d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a/span</value>
      <webElementGuid>8d5ce3db-fbd4-4450-a0f4-a755d97a245b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'arrow_forward' or . = 'arrow_forward')]</value>
      <webElementGuid>daae55e0-e52d-48bb-b863-d2d277a5ff09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
