<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NoElement</name>
   <tag></tag>
   <elementGuidId>9f8b9107-f85e-4c29-8e63-9e6ac5cf251d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div[2]/table/tfoot/tr/td/div/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.MuiTablePagination-displayedRows.css-1tvj1i3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8d9d2b91-fba3-46bc-bfb5-2f177abb201d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTablePagination-displayedRows css-1tvj1i3</value>
      <webElementGuid>ec075c41-0ff4-4d07-a729-db93472d3624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0–0 of 0</value>
      <webElementGuid>8bf91785-0720-4bbe-82c3-ef6190f8905a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-k008qs&quot;]/main[@class=&quot;MuiBox-root css-4rrr9a&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiTableContainer-root css-10lmdw7&quot;]/table[@class=&quot;MuiTable-root css-12t2pvv&quot;]/tfoot[@class=&quot;MuiTableFooter-root css-uab50h&quot;]/tr[@class=&quot;MuiTableRow-root MuiTableRow-footer css-10xs750&quot;]/td[@class=&quot;MuiTableCell-root MuiTableCell-footer MuiTableCell-sizeMedium MuiTablePagination-root css-1udrgdx&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-gutters MuiToolbar-regular MuiTablePagination-toolbar css-115xm6i&quot;]/p[@class=&quot;MuiTablePagination-displayedRows css-1tvj1i3&quot;]</value>
      <webElementGuid>c1a86cfc-d124-4392-b464-46b381e26053</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/table/tfoot/tr/td/div/p[2]</value>
      <webElementGuid>bf3c91eb-3982-4651-aee4-9a528e995132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[1]/following::p[2]</value>
      <webElementGuid>7f3d168a-1b2e-4f12-bdda-a97f72729796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[3]/following::p[2]</value>
      <webElementGuid>704445e3-d8ef-4230-bea7-964c9f94a4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::p[2]</value>
      <webElementGuid>120217df-3e55-4a14-b3d4-9b5a76a0fac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::p[2]</value>
      <webElementGuid>d67ad649-57f5-4b46-85ac-6d48016cdda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0–0 of 0']/parent::*</value>
      <webElementGuid>36fe3c94-57ae-4c06-9e5a-429f9def4162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>92662422-aac2-4942-abc0-b46ba17920d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '0–0 of 0' or . = '0–0 of 0')]</value>
      <webElementGuid>0880404f-b3eb-46ea-9ed1-0580e8202943</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
