<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EmptySting_CP_Phone number</name>
   <tag></tag>
   <elementGuidId>e4fe322c-8bcc-4f1b-bfc1-7454831aab27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-26-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid=&quot;input-phone-number-service-provider&quot;]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>beac11d6-db5e-49fa-a70b-ebe11c6c2e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium Mui-required css-xfkq2o</value>
      <webElementGuid>6c954785-6a97-4d3b-967b-8a79d055d985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-26-helper-text</value>
      <webElementGuid>092f2b0b-25ac-4bf9-8c46-b9b56864b744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phone number must be filled</value>
      <webElementGuid>51031794-a849-41f3-b302-f8588224916b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-26-helper-text&quot;)</value>
      <webElementGuid>d1724e30-f962-47ab-a3f3-c4d12bc8c15f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='mui-26-helper-text']</value>
      <webElementGuid>f859e7f4-e163-45ed-9e63-84499017260e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div[2]/div[2]/div/div/div/div/div/div[3]/p</value>
      <webElementGuid>cd26cbe1-efe6-4f2e-ae2f-55d9381afd7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::p[1]</value>
      <webElementGuid>e79b0e87-60b5-4b7d-9a4c-9e84124a5e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div[3]/p</value>
      <webElementGuid>0b116cda-74f2-402c-8a69-61e3d2121e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'mui-26-helper-text' and (text() = 'Phone number must be filled' or . = 'Phone number must be filled')]</value>
      <webElementGuid>1756b618-c905-4e69-beb8-076a0ab901d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
