<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_keyboard_arrow_up</name>
   <tag></tag>
   <elementGuidId>8798fd48-694e-4df4-9cac-2ea0599e2e16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiListItemButton-root.MuiListItemButton-gutters.MuiButtonBase-root.css-qv2vij > span.material-icons-outlined.notranslate.MuiIcon-root.MuiIcon-fontSizeSmall.css-xrdhw3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/nav/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e5230fde-2a95-4dfb-9289-2de66a69f127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons-outlined notranslate MuiIcon-root MuiIcon-fontSizeSmall css-xrdhw3</value>
      <webElementGuid>ee00d382-7c4c-4600-9aa3-25bb93af192f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c067ad77-165c-41c4-96c3-06af647afc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>icon-menu-2</value>
      <webElementGuid>05421d9f-15ec-4a57-96cd-36505e0ec771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>keyboard_arrow_up</value>
      <webElementGuid>ff5b781a-65c6-4e21-aa9f-4c0065db7c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-k008qs&quot;]/div[@class=&quot;MuiDrawer-root MuiDrawer-docked css-ute9xt&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiDrawer-paper MuiDrawer-paperAnchorLeft MuiDrawer-paperAnchorDockedLeft css-1dkyaee&quot;]/nav[@class=&quot;MuiList-root MuiList-padding MuiList-subheader css-1el0mim&quot;]/div[@class=&quot;MuiListItemButton-root MuiListItemButton-gutters MuiButtonBase-root css-qv2vij&quot;]/span[@class=&quot;material-icons-outlined notranslate MuiIcon-root MuiIcon-fontSizeSmall css-xrdhw3&quot;]</value>
      <webElementGuid>3122bd61-aae8-48c3-a5ae-932d821478f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/nav/div[2]/span</value>
      <webElementGuid>0f4870c7-7421-4738-86d0-df926cfb2a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Management'])[1]/following::span[1]</value>
      <webElementGuid>349e7527-6930-4b74-b46c-61e641587d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task Monitoring'])[1]/following::span[4]</value>
      <webElementGuid>f88a2aa3-5346-43de-b770-81ca4a30a47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Internal Setup'])[1]/preceding::span[5]</value>
      <webElementGuid>69b86d16-3483-4976-ad55-4215c0d90cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/preceding::span[9]</value>
      <webElementGuid>f3371b51-5ce5-4990-a543-4d8584997e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='keyboard_arrow_up']/parent::*</value>
      <webElementGuid>7509367c-94dc-4c8b-9909-074de1f52447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>db0a4cb9-d320-4668-b7af-9454aed0f723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'keyboard_arrow_up' or . = 'keyboard_arrow_up')]</value>
      <webElementGuid>43b21b7f-a80f-4ba3-afa4-7a45fb07b139</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
