<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Email doesnt valid</name>
   <tag></tag>
   <elementGuidId>2bc50d34-c874-4aff-95f2-6897e528f0c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='mui-30-helper-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-30-helper-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>dc653476-1c44-42ab-967a-3e4049f3ea9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-filled Mui-required css-xfkq2o</value>
      <webElementGuid>11ddd9ca-9682-40bd-90cd-e3351367d35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-30-helper-text</value>
      <webElementGuid>fc8c013f-03fa-4071-acb2-5424e927169c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email doesn't valid</value>
      <webElementGuid>5baf6fdb-1f99-4b04-accd-73c79e490583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-30-helper-text&quot;)</value>
      <webElementGuid>4993bcf9-0676-411c-9cb7-3bbec404516b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='mui-30-helper-text']</value>
      <webElementGuid>d11b9dc0-f36f-4f42-8627-8b0903c1daa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div/div[2]/div/div/div/div/div/div[3]/p</value>
      <webElementGuid>a57f9345-c0fa-4834-b7e3-b0f83d3dbefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::p[1]</value>
      <webElementGuid>6d97c0bf-6633-4714-8d51-cddeaf3707c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>1d9e0f4c-924c-4c35-9237-8c3f8ad95c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'mui-30-helper-text' and (text() = concat(&quot;Email doesn&quot; , &quot;'&quot; , &quot;t valid&quot;) or . = concat(&quot;Email doesn&quot; , &quot;'&quot; , &quot;t valid&quot;))]</value>
      <webElementGuid>ab60020d-0872-4120-b948-84602e666c7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
