<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Payment Details</name>
   <tag></tag>
   <elementGuidId>69ca60f5-f414-468e-ae63-547bcc5efceb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid=&quot;tabs-service-provider&quot;]/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-10-T-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5fff86c-e743-4084-b1a0-001fe81de3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4500945d-3c63-4bce-a489-626762a7daa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>d7c15e61-2984-4ab0-ab79-0d33b0199bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mui-10-P-1</value>
      <webElementGuid>646f87a2-f71b-4b2b-8bd7-ba2b7b9fbf51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-10-T-1</value>
      <webElementGuid>9c8a14da-b44b-45f5-b34a-10cba5e3e1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e5f0f4a2-8808-4940-8144-e4f9707161ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TabUnstyled-root Mui-selected css-c8w0k6</value>
      <webElementGuid>b9bcf34b-cb3d-4167-8735-fda365870934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>credit_cardPayment Details</value>
      <webElementGuid>8844a250-89f9-409a-83b5-60315c29228f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-10-T-1&quot;)</value>
      <webElementGuid>d8ff639e-9d0d-4a7c-bbca-7491a375c104</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mui-10-T-1']</value>
      <webElementGuid>758caf69-f968-4c12-802a-be763254ba04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div/div/button[2]</value>
      <webElementGuid>a24d6306-4150-4652-85ed-e69af728c420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Details'])[2]/preceding::button[1]</value>
      <webElementGuid>cd54fbac-7816-41a3-9f69-78317091a7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>98a6f0c7-fa05-41cc-b989-0f44dcd878a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'mui-10-T-1' and (text() = 'credit_cardPayment Details' or . = 'credit_cardPayment Details')]</value>
      <webElementGuid>179e03de-b63e-4eb2-9b17-a297ff2d74e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
