<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_companyProfile</name>
   <tag></tag>
   <elementGuidId>f06690d6-4c03-425b-82d7-8dc8668c21a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid=&quot;tabs-service-provider&quot;]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-10-T-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0af7dc20-cd2c-44c5-b6bb-a7dedd0e5c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>95585f61-c049-45c5-a7f3-d12f522579a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>ce92c044-a9fb-440f-815e-771c32eb2d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mui-10-P-0</value>
      <webElementGuid>27ff35c2-dea8-487a-8b70-4ad39e23e105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-10-T-0</value>
      <webElementGuid>5f31c3f4-0511-4a9d-b707-674574c631d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cbf629a6-9fd0-4491-8273-360a15cf7695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TabUnstyled-root Mui-selected css-c8w0k6</value>
      <webElementGuid>f2de4c86-f99f-4be8-97b8-5c3c1d0bd13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>home_workCompany Profile</value>
      <webElementGuid>00770ff5-5366-47bc-abec-d9176d87ea8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-10-T-0&quot;)</value>
      <webElementGuid>e24a8a3f-b8fa-4c61-9f6f-a5140035ce4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mui-10-T-0']</value>
      <webElementGuid>d72e6286-0e6b-4c25-bf87-f2edc88ee2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/div/div/button</value>
      <webElementGuid>dbe93ff5-fbba-4f90-8b5f-54c9019b57d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Logo'])[1]/preceding::button[2]</value>
      <webElementGuid>fc6535dc-fe39-4784-a6d5-a747ddaa0b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>c6c9a71e-4e4e-4412-b35d-a7a08b5b6e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'mui-10-T-0' and (text() = 'home_workCompany Profile' or . = 'home_workCompany Profile')]</value>
      <webElementGuid>47f8023d-cf2e-48a9-b3fa-85e2654906ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
